factsBox: use GObject.registerClass()
Just this class had been handled differently in e2a5edf
("Port GObject classes to JS6 classes"). Handle them like all others;
this is required for GNOME 3.34. Fixes this problem:

    gnome-shell[9973]: TypeError: this.factsBox.refresh is not a function

Under GNOME 3.32, this commit causes the following error message:

    gnome-shell[7033]: Extension "contact@projecthamster.org" had error:
    TypeError:GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)

Thus it breaks compatibility with GNOME 3.32.